### ISSUE TITLE
Design thoughts for the article

### ISSUE THREAD

**Issue by arrowtype** [graphicore/varla-varfo#2]
Feel free to take the with a grain of salt / disregard whatever you disagree with. But, here are some thoughts on how the article may be more reader-friendly and effective.

- Make the Calibration Widget something that is inline of the article, rather than a modal / "separate page." It’s really cool to try this, then see the measurements size to real measurements!
- Maybe, make SVG graphics that are little rulers of some kind, to show that these are really units of measurement. These could be labeled as "CSS Units" before calibration, then "Calibrated real-world units" after
- The list of "more use cases" would be much easier to read as a bulleted `ul` list.
- A clear call to action (like a big button) of "add more use cases" would be helpful to gather more use cases from more people.

**Comment by arrowtype** [comment]
Oh, and a few other items that might be helpful options for the calibration widget:
- 3 inches
- 10 centimeters
- Standard 3.5 inch Post-It note

**Comment by graphicore** [comment]
Thanks, all good points.

More calibration items:

* DIN-A 1-6 paper sizes
* US paper sizes standards

Generally, stuff that one has lying around.

**Comment by graphicore** [comment]
> * Maybe, make SVG graphics that are little rulers of some kind, to show that these are really units of measurement. These could be labeled as "CSS Units" before calibration, then "Calibrated real-world units" after

This will be the last step, but I agree some illustrations would be good.

One illustration I'd really like to have is a poster design compared to a flyer at the same size next to each other.
