### ISSUE TITLE
Potential use cases

### ISSUE THREAD

**Issue by arrowtype** [graphicore/varla-varfo#3]
A brainstorm of some potential usecases. Not totally sure whether any of these are duplicates. Where should I post these?

- E-commerce (!!). People always want to know the physical size of the book/phone/watch/postcard/shoe/pen/whatever they are ordering. What better way than to just show it on the website?
- Ruler webapp for smartphones. Kids would use this.
- Drawing / tracing apps for the iPad or other tablets (artists need to control the pysical sizing of drawings)
- Photo development apps? For instance, you could match the sizing of 4"x6" prints, or 35mm film negatives
- Post-It note templates – imagine a wall of monitors with columns for Post-It notes. This could very much be a thing at companies like IBM who do "Design Thinking" corporate workshops, along with hundreds of Post-It notes.

**Comment by graphicore** [comment]
I had the e-commerce one in that [previous](https://github.com/graphicore/varla-vafo/blob/main/explorations/techniques/absolute_units_evaluation.html) [shorter piece](https://graphicore.github.io/varla-vafo/explorations/techniques/absolute_units_evaluation) :smile::

> * Make size matching simple. E.g. for online shopping, decide the correct size of gloves by matching the users hand on the screen directly.

also:

> * Give designers a correct preview impression of a website at a specific screen size. E.g. for a specific phone model.

From the  article source, but unstructured (wrong place to put anyways) and not all thought through:

        more use cases:
          - print proofing/designer preview. We can help reducing paper
            wastage!
          - Effective web proofing by correctly scaling to actual
            e.g. phone-screen sizes.
          - optical size proofing for type design
          - getting an impression what the default viewing distance is
            supposed to be on certain devices, as it is not easy to to
            do on the spot.

          - touch device UI must be touched with physical fingers,
            hence controls designed with physical sizes are best practice.

          - the web platform usage diversifies as it is becoming more ubiquitous.

          - the web platform is becoming more ubiquitous, not all use cases
            fit well into the "reference pixel" approach. Sometimes
            target screen and viewing distance could be very well known
            and hence a direct way of designing for these target could be
            desirable. In web, the flexibility of the CSS-unit approach
            requires that there's a scroll somewhere. Paged media can't
            afford this. Where a user can't scroll, e.g. a digital poster
            on a screen, that is not interactive, pages become important
            and alse that the designer can control the viewing distance
            assumptions. 
          - We can control for different device sizes even when designing
            with real world units, though a support in media-queries would
            help a lot.
          - hi-res screens are so good now, we can anchor to physical units
            and won't get blurry lines.

          - what about e.g. font-sizes for legal print, are there absolute
            requirements? "legible" is one of them, but fonts becoming regularly
            smaller than e.g. 12 pt because the device defaults to 20 inches
            viewing distance instead of 28 inches may be unfortunate.
