### ISSUE TITLE
Content thoughts for the article

### ISSUE THREAD

**Issue by arrowtype** [graphicore/varla-varfo#4]
The article starts with the following quote:

> It is possible that most members of the CSSWG and most browser engineers are wrong, that there's a big flaw in the collective reasoning, and that one way or another, this is actually a good idea. If you think so, start by understanding the arguments against, then build a strong case debunking them, and explain why you're right.
> 
> Merely stating that there's no downside isn't going to be convincing.

...but then doesn’t actually cite any of those arguments against it, to then debate them.

As a reader, I’d like to see a section of headings that are arguments against this, then a short refutation of each argument.

Here’s one example of this kind of "argument and response" format: https://www.theguardian.com/environment/climate-consensus-97-per-cent/2014/may/06/top-ten-global-warming-skeptic-arguments-debunked

**Comment by graphicore** [comment]
Yes, I think we have to collect arguments from the public discussions and discuss them in the article. Maybe we can categorize them to make it more efficient and structured.

**Comment by arrowtype** [comment]
Yeah, probably that would make the best argument. I love the start & the calibration tool, though! I was more excited than I expected to measure the squares and see that they really were 1 cm & 1 inch.

**Comment by graphicore** [comment]
This was a piece of work, but I think the "Debunking" section is good now. I would be thankful for feedback.

I'm working on Use Cases and the Roadmap now, but the Debunking part was the hardest and most important.
