### ISSUE TITLE
Reword/drop debunking

### ISSUE THREAD

**Issue by m4rc1e** [graphicore/varla-varfo#7]
I'd drop this section since doesn't add much and may aggravate the situation.

**Comment by graphicore** [comment]
Reword is fine, but it's an explicitly stated requirement to discuss those counter arguments. I didn't come up with the title "debunking", just took it from another comment. Any other name would do for me, do you have a suggestion?

**Comment by graphicore** [comment]
When you say drop the section, the section goes from Debunking to (excluding) Use Cases. Do you mean to drop it all or just the part directly under the heading?

**Comment by graphicore** [comment]
"Discourse"

**Comment by graphicore** [comment]
"Debate"

**Comment by m4rc1e** [comment]
Apologies, I wasn't clear enough. Imo this whole section can be deleted.

<img width="1080" alt="Screenshot 2021-03-08 at 14 01 39" src="https://user-images.githubusercontent.com/7525512/110331269-cfddfd80-8016-11eb-963f-016961a28fad.png">

**Comment by graphicore** [comment]
I agree, that can be done.
